apiVersion: apps/v1
kind: Deployment
metadata:
  name: vchevill-playground
  labels:
    app: will
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
